# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_main_dummy_default_controller:
    resource: "@MainBundle/Controller/DefaultController.php"
    type:     annotation